name: todo_app
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  intl: 0.15.0
  tuple: 1.0.1
  date_utils: 0.0.1
  sqflite: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg


  fonts:
    - family: Raleway-Regular
      fonts:
        - asset: assets/Raleway-Regular.ttf

    - family: OpenSans-Light
      fonts:
        - asset: assets/OpenSans-Light.ttf